using System;
using System.Text;
using System.Data.Common;
using System.Diagnostics.CodeAnalysis;
using System.Diagnostics;
using System.Data;
using System.Collections.Generic;

namespace Apps72.Dev.Data
{
    /// <summary>
    /// Database command management
    /// </summary>
    /// <example>
    /// <code>
    /// public class SqlDatabaseCommand : DatabaseCommandBase&lt;SqlConnection, SqlCommand, SqlParameterCollection, SqlTransaction, SqlException&gt;
    /// {
    ///     public SqlDatabaseCommand(SqlConnection connection) : base(connection) { }
    /// }
    /// </code>
    /// </example>
    [SuppressMessage("Microsoft.Design", "CA1005:AvoidExcessiveParametersOnGenericTypes")]
    [DebuggerDisplay("{CommandText}")]
    public abstract class DatabaseCommandBase : IDatabaseCommandBase
    {

        #region EVENTS

        /// <summary>
        /// Signature for ExceptionOccured event
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        public delegate void ExceptionOccuredEventHandler(object sender, ExceptionOccuredEventArgs e);

        /// <summary>
        /// Event raised when an SQL Exception occured (in Execute Methods)
        /// </summary>
        public event ExceptionOccuredEventHandler ExceptionOccured;

        #endregion

        #region CONSTRUCTORS

        /// <summary>
        /// Create a command for a SQL Server connection
        /// </summary>
        /// <param name="command">Active command with predefined CommandText and Connection</param>
        /// <param name="transaction">The transaction in which the SQL Query executes</param>
        /// <param name="commandTimeout">the wait time (in seconds) before terminating the attempt to execute a command and generating an error.</param>
        protected DatabaseCommandBase(DbCommand command, DbTransaction transaction, int commandTimeout)
        {
            this.ThrowException = true;
            this.Connection = command != null ? command.Connection : null;
            this.Command = command;

            if (transaction != null)
            {
                this.Transaction = transaction;
            }

            if (commandTimeout >= 0)
                this.Command.CommandTimeout = commandTimeout;

            this.CommandText = new StringBuilder(command != null ? command.CommandText : string.Empty);
        }

        #endregion

        #region PROPERTIES

        /// <summary>
        /// Gets or sets the sql query
        /// </summary>
        public virtual System.Text.StringBuilder CommandText { get; set; }

        /// <summary>
        /// Gets or sets the command type
        /// </summary>
        public virtual System.Data.CommandType CommandType { get; set; }

        /// <summary>
        /// Gets or sets the current active connection
        /// </summary>
#if SQL_CLR
        public virtual DbConnection Connection { get; set; }
#else
        protected virtual DbConnection Connection { get; set; }
#endif

        /// <summary>
        /// Gets or sets the current DbCommand
        /// </summary>
        protected virtual DbCommand Command { get; set; }

        /// <summary>
        /// Gets or sets the current transaction
        /// </summary>
        public virtual IDbTransaction Transaction
        {
            get
            {
                return this.Command.Transaction;
            }
            set
            {
                this.Command.Transaction = value as DbTransaction;
            }
        }

        /// <summary>
        /// Gets sql parameters of the query
        /// </summary>
        public virtual IDataParameterCollection Parameters
        {
            get
            {
                return this.Command.Parameters;
            }
        }

        /// <summary>
        /// Enable or disable the raise of exceptions when queries are executed.
        /// Default is True (Enabled).
        /// </summary>
        public virtual bool ThrowException { get; set; }

        /// <summary>
        /// Gets the last raised exception 
        /// </summary>
        public virtual System.Runtime.InteropServices.ExternalException Exception { get; private set; }

        /// <summary>
        /// Set this property to log the SQL generated by this class to the given delegate. 
        /// For example, to log to the console, set this property to Console.Write.
        /// </summary>
        public virtual Action<string> Log { get; set; }

        #endregion

        #region METHODS

        /// <summary>
        /// Gets the CommandText formatted with specified format
        /// </summary>
        /// <param name="format">Use Text to format as Simple SQL Query or use HTML to format as Colored SQL Query.</param>
        /// <returns>Formatted query</returns>
        public virtual string GetCommandTextFormatted(QueryFormat format)
        {
            string sql = this.CommandText.ToString();
            if (String.CompareOrdinal(sql, this.Command.CommandText) != 0)
                this.Command.CommandText = sql;

            return new CommandTextFormatted(this.Command).GetSqlFormatted(format);
        }

        /// <summary>
        /// Delete the CommandText and the all sql parameters
        /// </summary>
        public virtual void Clear()
        {
            this.CommandText.Length = 0;
            this.Parameters.Clear();
        }

        /// <summary>
        /// Prepare a query
        /// </summary>
        public virtual void Prepare()
        {
            this.Command.CommandText = this.CommandText.ToString();
            this.Command.Prepare();
        }

        /// <summary>
        /// Begin a transaction into the database
        /// </summary>
        /// <returns>Transaction</returns>
        public virtual IDbTransaction TransactionBegin()
        {
            if (this.Log != null)
                this.Log.Invoke("BEGIN TRANSACTION");

            if (!this.Connection.ContainsDataInjectionDataTable())
            {
                this.Command.Transaction = this.Command.Connection.BeginTransaction();
                return this.Command.Transaction;
            }
            else
            {
                return null;
            }
        }

        /// <summary>
        /// Commit the current transaction to the database
        /// </summary>
        public virtual void TransactionCommit()
        {
            if (this.Command != null && this.Command.Transaction != null)
            {
                if (this.Log != null)
                    this.Log.Invoke("COMMIT");

                if (!this.Connection.ContainsDataInjectionDataTable())
                {
                    this.Command.Transaction.Commit();
                }
            }
        }

        /// <summary>
        /// Rollback the current transaction 
        /// </summary>
        public virtual void TransactionRollback()
        {
            if (this.Command != null && this.Command.Transaction != null)
            {
                if (this.Log != null)
                    this.Log.Invoke("ROLLBACK");

                if (!this.Connection.ContainsDataInjectionDataTable())
                {
                    this.Command.Transaction.Rollback();
                }
            }
        }

        /// <summary>
        /// Execute query and return results by using a Datatable
        /// </summary>
        /// <returns>DataTable of results</returns>
        public virtual System.Data.DataTable ExecuteTable()
        {
            ResetException();

            try
            {

                System.Data.DataTable data = new System.Data.DataTable();

                string sql = this.CommandText.ToString();
                if (String.CompareOrdinal(sql, this.Command.CommandText) != 0)
                    this.Command.CommandText = sql;

                if (this.Log != null)
                    this.Log.Invoke(this.Command.CommandText);

                // If UnitTest activated, invoke the "Get Method" to retrieve custom data
                if (this.Connection.ContainsDataInjectionDataTable())
                {
                    return this.Connection.InvokeAndReturnData(this.Command);
                }

                // Send the request to the Database server
                using (DbDataReader dr = this.Command.ExecuteReader())
                {
                    data.Load(dr);
                    return data;
                }
            }
            catch (DbException ex)
            {
                return ThrowSqlExceptionOrDefaultValue<System.Data.DataTable>(ex);
            }

        }

        /// <summary>
        /// Execute the query and return an array of new instances of typed results filled with data table result.
        /// </summary>
        /// <typeparam name="TReturn">Object type</typeparam>
        /// <returns>Array of typed results</returns>
        /// <example>
        /// <code>
        ///   Employee[] emp = cmd.ExecuteTable&lt;Employee&gt;();
        ///   var x = cmd.ExecuteTable&lt;Employee&gt;();
        /// </code>
        /// <remarks>
        ///   Result object property (ex. Employee.Name) may be tagged with the ColumnAttribute 
        ///   to set which column name (ex. [Column("Name")] must be associated to this property.
        /// </remarks>
        /// </example>
        public virtual IEnumerable<TReturn> ExecuteTable<TReturn>()
        {
            System.Data.DataTable table = this.ExecuteTable();
            return SqlDataTypedConvertor.DataTableTo<TReturn>(table);
        }

        /// <summary>
        /// Execute the query and return an array of new instances of typed results filled with data table result.
        /// </summary>
        /// <typeparam name="TReturn">Object type</typeparam>
        /// <param name="itemOftype"></param>
        /// <returns>Array of typed results</returns>
        /// <example>
        /// <code>
        ///   Employee emp = new Employee();
        ///   var x = cmd.ExecuteTable(new { emp.Age, emp.Name });
        ///   var y = cmd.ExecuteTable(new { Age = 0, Name = "" });
        /// </code>
        /// <remarks>
        ///   Result object property (ex. Employee.Name) may be tagged with the ColumnAttribute 
        ///   to set which column name (ex. [Column("Name")] must be associated to this property.
        /// </remarks>
        /// </example>
        public virtual IEnumerable<TReturn> ExecuteTable<TReturn>(TReturn itemOftype)
        {
            return ExecuteTable<TReturn>();
        }

        /// <summary>
        /// Execute the query and return an array of new instances of typed results filled with data table result.
        /// </summary>
        /// <typeparam name="TReturn">Object type</typeparam>
        /// <param name="converter">Conveter method to return a typed object from DataRow</param>
        /// <returns>Array of typed results</returns>
        public virtual IEnumerable<TReturn> ExecuteTable<TReturn>(Func<System.Data.DataRow, TReturn> converter)
        {
            System.Data.DataTable table = this.ExecuteTable();

            TReturn[] results = new TReturn[table.Rows.Count];
            for (int i = 0; i < table.Rows.Count; i++)
            {
                results[i] = converter.Invoke(table.Rows[i]);
            }

            return results;
        }

        /// <summary>
        /// Execute the query and return the count of modified rows
        /// </summary>
        /// <returns>Count of modified rows</returns>
        public virtual int ExecuteNonQuery()
        {
            ResetException();

            try
            {

                string sql = this.CommandText.ToString();

                if (String.CompareOrdinal(sql, this.Command.CommandText) != 0) this.Command.CommandText = sql;

                if (this.Log != null)
                    this.Log.Invoke(this.Command.CommandText);

                // If UnitTest activated, invoke the "Get Method" to retrieve custom data
                if (this.Connection.ContainsDataInjectionDataTable())
                {
                    DataTable data = this.Connection.InvokeAndReturnData(this.Command);
                    if (data != null && data.Rows != null)
                        return data.Rows.Count;
                    else
                        return 0;
                }

                // Send the request to the Database server
                return this.Command.ExecuteNonQuery();
            }
            catch (DbException ex)
            {
                return ThrowSqlExceptionOrDefaultValue<int>(ex);
            }

        }

        /// <summary>
        /// Execute the query and return the first column of the first row of results
        /// </summary>
        /// <returns>Object - Result</returns>
        public virtual object ExecuteScalar()
        {
            ResetException();

            try
            {

                string sql = this.CommandText.ToString();
                if (String.CompareOrdinal(sql, this.Command.CommandText) != 0)
                    this.Command.CommandText = sql;

                if (this.Log != null)
                    this.Log.Invoke(this.Command.CommandText);

                // If UnitTest activated, invoke the "Get Method" to retrieve custom data
                if (this.Connection.ContainsDataInjectionDataTable())
                {
                    DataTable data = this.Connection.InvokeAndReturnData(this.Command);
                    if (data != null && data.Rows != null && data.Rows.Count > 0 && data.Columns != null && data.Columns.Count > 0)
                        return data.Rows[0][0];
                    else
                        return null;
                }

                // Send the request to the Database server
                return this.Command.ExecuteScalar();
            }
            catch (DbException ex)
            {
                return ThrowSqlExceptionOrDefaultValue<object>(ex);
            }

        }

        /// <summary>
        /// Execute the query and return the first column of the first row of results
        /// </summary>
        /// <typeparam name="TReturn">Return type</typeparam>
        /// <returns>Result</returns>
        public virtual TReturn ExecuteScalar<TReturn>()
        {
            object scalar = this.ExecuteScalar();

            if (scalar == null || scalar == DBNull.Value)
                return default(TReturn);
            else
                return (TReturn)scalar;

        }

        /// <summary>
        /// Execute the query and return the first row of results    
        /// </summary>
        /// <returns>First row of results</returns>
        public virtual System.Data.DataRow ExecuteRow()
        {
            System.Data.DataTable result = this.ExecuteTable();

            if (result == null)
                return null;

            if (result.Rows.Count > 0)
                return result.Rows[0];
            else
                return null;
        }

        /// <summary>
        /// Execute the query and return a new instance of TReturn with the first row of results
        /// </summary>
        /// <typeparam name="TReturn">Object type</typeparam>
        /// <returns>First row of results</returns>
        /// <example>
        /// <code>
        ///   Employee emp = cmd.ExecuteRow&lt;Employee&gt;();
        /// </code>
        /// <remarks>
        ///   Result object property (ex. Employee.Name) may be tagged with the ColumnAttribute 
        ///   to set which column name (ex. [Column("Name")] must be associated to this property.
        /// </remarks>
        /// </example>
        public virtual TReturn ExecuteRow<TReturn>()
        {
            if (SqlDataTypedConvertor.IsPrimitive(typeof(TReturn)))
            {
                return this.ExecuteScalar<TReturn>();
            }
            else
            {
                System.Data.DataRow row = this.ExecuteRow();
                return SqlDataTypedConvertor.DataRowTo<TReturn>(row);
            }
        }

        /// <summary>
        /// Execute the query and fill the specified TReturn object with the first row of results
        /// </summary>
        /// <typeparam name="TReturn">Object type</typeparam>
        /// <param name="itemOftype"></param>
        /// <returns>First row of results</returns>
        /// <example>
        /// <code>
        ///   Employee emp = new Employee();
        ///   var x = cmd.ExecuteRow(new { emp.Age, emp.Name });
        ///   var y = cmd.ExecuteRow(new { Age = 0, Name = "" });
        ///   var z = cmd.ExecuteRow(emp);
        /// </code>
        /// <remarks>
        ///   Result object property (ex. Employee.Name) may be tagged with the ColumnAttribute 
        ///   to set which column name (ex. [Column("Name")] must be associated to this property.
        /// </remarks>
        /// </example>
        public virtual TReturn ExecuteRow<TReturn>(TReturn itemOftype)
        {
            System.Data.DataRow row = this.ExecuteRow();

            return SqlDataTypedConvertor.DataRowTo<TReturn>(row, itemOftype);
        }

        /// <summary>
        /// Execute the query and fill the specified TReturn object with the first row of results
        /// </summary>
        /// <typeparam name="TReturn">Object type</typeparam>
        /// <param name="converter">Conveter method to return a typed object from DataRow</param>
        /// <returns>First row of results</returns>
        public virtual TReturn ExecuteRow<TReturn>(Func<System.Data.DataRow, TReturn> converter)
        {
            System.Data.DataRow row = this.ExecuteRow();
            return converter.Invoke(row);
        }

        /// <summary>
        /// Raises the ExceptionOccured event.
        /// </summary>
        /// <param name="e"></param>
        protected virtual void OnExceptionOccured(ExceptionOccuredEventArgs e)
        {
            if (this.ExceptionOccured != null)
            {
                ExceptionOccured(this, e);
            }
        }

        /// <summary>
        /// Dispose the object and free ressources
        /// </summary>
        public void Dispose()
        {
            Dispose(true);
        }

        /// <summary>
        /// Dispose the object and free ressources
        /// </summary>
        /// <param name="disposing"></param>
        protected virtual void Dispose(bool disposing)
        {
            if (disposing)
            {

            }

            if (this.Command.Transaction != null)
                this.Command.Transaction.Dispose();

            if (this.Command != null)
                this.Command.Dispose();
        }

#if !SQL_CLR

        /// <summary>
        /// Dispose the object and free ressources
        /// </summary>
        ~DatabaseCommandBase()
        {
            Dispose(false);
        }

#endif

        #endregion

        #region PRIVATE

        /// <summary>
        /// Set the last raised exception to null
        /// </summary>
        protected virtual void ResetException()
        {
            this.Exception = null;
        }

        /// <summary>
        /// Raise the Exception if the ThrowException property is set to TRUE
        /// </summary>
        /// <typeparam name="T">Type</typeparam>
        /// <param name="ex">Exception</param>
        /// <returns></returns>
        protected virtual T ThrowSqlExceptionOrDefaultValue<T>(DbException ex)
        {
            this.Exception = ex;

            OnExceptionOccured(new ExceptionOccuredEventArgs() { Exception = this.Exception });

            if (ex != null)
            {
                if (this.ThrowException) throw ex;
            }

            return default(T);
        }

        #endregion
    }
}
