# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]
        frameworks: [net45,net6.0,netcoreapp3.1]

    runs-on: windows-latest 
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.418'

    - name: Execute dotnet build 
      run: dotnet build Src\Core\Core.csproj -c $env:Configuration -f $env:Framework
      env:
        Configuration: ${{ matrix.configuration }}
        Framework: ${{ matrix.frameworks }}

# Test want to get SQL DB connected
#    - name: Execute unit tests
#      run: dotnet test -c $env:Configuration 
#      env:
#        Configuration: ${{ matrix.configuration }}
